# Generated by Django 6.0.6 on 2026-06-11 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sport_type', models.CharField(max_length=100)),
                ('distance', models.FloatField(default=0)),
                ('elapsed_time', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('average_heartrate', models.FloatField(blank=True, null=True)),
                ('total_elevation_gain', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StravaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.BigIntegerField(unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_expires_at', models.BigIntegerField(default=0)),
                ('athlete_name', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stravaprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
